// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;




import com.revrobotics.CANSparkBase.IdleMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.CANSparkFlex;
import com.revrobotics.CANSparkLowLevel.MotorType;
import com.revrobotics.CANSparkMax;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.SubsystemBase;

/**
 *
 */
public class Shamper extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private CANSparkMax bottomLeft;
private CANSparkMax bottomRight;
private CANSparkFlex topLeft;
private CANSparkFlex topRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private CANSparkMax bottomLeft2;

public double defaultRPM = 240;
private double maxRPMVortex = 6780;
private double maxRPMNeo550 = 11000;
private double gearRatioDoubleNeo550 = maxRPMNeo550 / 3;
private double gearRatioSingleNeo550 = maxRPMNeo550 / 10;

public double neo550TargetSpeed = defaultRPM;
public double vortexTargetSpeed = defaultRPM;
public double neo550MeasuredSpeed = neo550TargetSpeed;
public double vortexMeasuredSpeed = vortexTargetSpeed;
public double singleNeo550MeasuredSpeed = neo550TargetSpeed;
private double neo550CorrectionFactor = 0;
private double singleNeo550CorrectionFactor = 0;
private double vortexCorrectionFactor = 0;
    /**
    *
    */
    public Shamper() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
bottomLeft = new CANSparkMax(25, MotorType.kBrushless);
 
   
bottomLeft.setInverted(true);
bottomLeft.setIdleMode(IdleMode.kBrake);
bottomLeft.burnFlash();
  

bottomRight = new CANSparkMax(26, MotorType.kBrushless);
 
   
bottomRight.setInverted(false);
bottomRight.setIdleMode(IdleMode.kBrake);
bottomRight.burnFlash();
  

topLeft = new CANSparkFlex(27, MotorType.kBrushless);
 
   
topLeft.setInverted(true);
topLeft.setIdleMode(IdleMode.kBrake);
topLeft.burnFlash();
  

topRight = new CANSparkFlex(28, MotorType.kBrushless);
 
   
topRight.setInverted(false);
topRight.setIdleMode(IdleMode.kBrake);
topRight.burnFlash();
  


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
bottomLeft2 = new CANSparkMax(20, MotorType.kBrushless);
 
   
bottomLeft2.setInverted(false);
bottomLeft2.setIdleMode(IdleMode.kBrake);
bottomLeft2.burnFlash();
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void runAll() {
        neo550TargetSpeed = SmartDashboard.getNumber("BL-RPM", defaultRPM);
        vortexTargetSpeed = SmartDashboard.getNumber("TL-RPM", defaultRPM);
        neo550MeasuredSpeed = SmartDashboard.getNumber("Neo 550 Measured Speed", defaultRPM);
        vortexMeasuredSpeed = SmartDashboard.getNumber("Vortex Measured Speed", defaultRPM);
        singleNeo550MeasuredSpeed = SmartDashboard.getNumber("Single Neo 550 Measured Speed", defaultRPM);
        neo550CorrectionFactor = neo550TargetSpeed / neo550MeasuredSpeed;
        vortexCorrectionFactor = vortexTargetSpeed / vortexMeasuredSpeed;
        singleNeo550CorrectionFactor = neo550TargetSpeed / singleNeo550MeasuredSpeed;
        bottomLeft.set((SmartDashboard.getNumber("BL-RPM", defaultRPM) / gearRatioDoubleNeo550) * neo550CorrectionFactor);
        bottomLeft2.set((SmartDashboard.getNumber("BL-RPM", defaultRPM) / gearRatioSingleNeo550) * neo550CorrectionFactor);
        bottomRight.set((SmartDashboard.getNumber("BR-RPM", defaultRPM) / gearRatioDoubleNeo550) * neo550CorrectionFactor);
        topLeft.set((SmartDashboard.getNumber("TL-RPM", defaultRPM) / maxRPMVortex) * vortexCorrectionFactor);
        topRight.set((SmartDashboard.getNumber("TR-RPM", defaultRPM) / maxRPMVortex) * vortexCorrectionFactor);
    }

    public void stopall() {
        bottomLeft.set(0);
        bottomLeft2.set(0);
        bottomRight.set(0);
        topLeft.set(0);
        topRight.set(0);
    }



}

